namespace: template-app

resources:
- ns.yaml
- template-app.yaml
- operators/cloudnativepg/cnpg-example-database.yaml
#- helm.yaml

secretGenerator:
- name: template-app
  files:
  - etc/.secrets/example-secret
