---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-app
  labels:
    role: template-app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: template-app
  template:
    metadata:
      labels:
        role: template-app
    spec:
      containers:
      - name: template-app
        image: busybox:latest
        imagePullPolicy: Always
        command: [ "sh", "-c", "sleep infinity" ]
        volumeMounts:
        - name: template-app-data
          mountPath: /data
          readOnly: true
      volumes:
      - name: template-app-data
        persistentVolumeClaim:
          claimName: template-app-data
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: template-app-data
spec:
  # Define storageClassName to override default storageClass on cluster (e.g., weka)
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
