---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-template
  labels:
    role: app-template
spec:
  replicas: 1
  selector:
    matchLabels:
      role: app-template
  template:
    metadata:
      labels:
        role: app-template
    spec:
      containers:
      - name: app-template
        image: busybox:latest
        imagePullPolicy: Always
        command: [ "sh", "-c", "sleep infinity" ]
        volumeMounts:
        - name: app-template-data
          mountPath: /data
          readOnly: true
      volumes:
      - name: app-template-data
        persistentVolumeClaim:
          claimName: app-template-data
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-template-data
spec:
  # Define storageClassName to override default storageClass on cluster (e.g., weka)
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
