---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    release: sdf-k8s01
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: web