
# the following will create two secrets. one-secret is just a literal value of the username (be careful not to put anything sensitive here).
# the auth-secret k8s secret is derived from the contents of the (relative) filepath etc/.secrets/somefile.
# as the entries are yaml arrays, you can put multiple key/value pairs in each secret.

# for the population of the etc/.secrets/ files, one may manually enter the sensitive data into the files directly, or see the Makefile for a
# programmatic way of retrieving the values from vault.
 
secretGenerator:
- name: one-secret
  literals:
  - username=backup
- name: auth-secret
  files:
  - auth=etc/.secrets/somefile

# this option prevents secrets (and config maps) from having a hash (version) appended to the names. this is useful for when you do not care about 
# kustomize pinning the version of the Secret to the pod consuming it - ie don't restart the pod if the Secret changes.

generatorOptions:
  disableNameSuffixHash: true
